name: Add assignee to PRs
on:
  pull_request:
    types: [ opened, reopened ]
permissions:
  pull-requests: write
jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - name: assign-author
        # ignore the pull requests opened from PR because token is not correct
        if: github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]'
        uses: toshimaru/auto-author-assign@16f0022cf3d7970c106d8d1105f75a1165edb516

